### ISSUE TITLE
Add Feature: input mix

### ISSUE THREAD

**Issue by JanBezler** [BETAFPV/BETAFPV_Configurator#14]
It would be great to add possibility to mix input.
For example if I want  use LiteRadio 3 to control V-tail airplane I can do that only at FC level.
Also mixing button input with any axis input can be useful in some situations.

**Comment by HWT662988** [comment]
It's been added and you can find it here:
![image](https://user-images.githubusercontent.com/45007731/152904443-fb3db1a3-b761-4688-a25c-49217c054245.png)
