### ISSUE TITLE
Cetus Pro FC v1.2, Configurator v1.1.0 on Mac, No configuration received

### ISSUE THREAD

**Issue by ipolikarpov** [BETAFPV/BETAFPV_Configurator#17]
Hello!

I'm using Configurator 1.1.0 on Mac, usb connection is ok, because I can flash FC firmware.
But when I try to connect Cetus Pro (FC v1.2) I receive a message "No configuration received". I tried all available FC firmwares, It does not help.

**Comment by th0m4sek** [comment]
same on windows (running in virtualbox)

**Comment by fpvntt** [comment]
Same here. No configuration received on mac

**Comment by maxfield-allison** [comment]
Same on Windows. really need to be able to adjust it for props out. not sure why this has been sitting here in a broken state for so long.

**Comment by gaisin** [comment]
I have same issue with Cetus Pro and Mac. BETAFPV Configurator does not respond after hitting "Connect", if I'm trying to connect to BetaFlight Configurator, I can see logs:
```
2022-10-15 @05:24:02 -- Serial port successfully opened with ID: 4
2022-10-15 @05:24:12 -- No configuration received within 10 seconds, communication failed
2022-10-15 @05:24:12 -- Serial port successfully closed
```

**Comment by wenzhicode** [comment]
Hi, @ipolikarpov @gaisin @th0m4sek @maxfield-allison @fpvntt , I am one of the developers for this configurator, after a few months away, I am now back to continue maintaining the project.
I appreciate it if you would like to fill it out in the format below。

board version:
problem:
need help:

**Comment by pjcjonas** [comment]
We cant tell you the board version, the problem or anything cause we cant connect. 
![image](https://user-images.githubusercontent.com/2368056/212465737-21e88a22-a589-48e8-92e9-2a8961ce2212.png)
The problem is identified in the message thread... 

board version: ??? No idea. possibly 1.3
problem: 
![image](https://user-images.githubusercontent.com/2368056/212465770-8f2fdb66-1b33-48fc-9b87-2a9a7c533894.png)

need help:

**Comment by pjcjonas** [comment]
![image](https://user-images.githubusercontent.com/2368056/212465821-b192a164-ce08-45fd-a972-c73ca1eb18ab.png)

**Comment by wenzhicode** [comment]
> We cant tell you the board version, the problem or anything cause we cant connect. ![image](https://user-images.githubusercontent.com/2368056/212465737-21e88a22-a589-48e8-92e9-2a8961ce2212.png) The problem is identified in the message thread...
> 
> board version: ??? No idea. possibly 1.3 problem: ![image](https://user-images.githubusercontent.com/2368056/212465770-8f2fdb66-1b33-48fc-9b87-2a9a7c533894.png)
> 
> need help:

This problem is the FC board did not response when configurator try to send message to it.




> I'm using Configurator 1.1.0 on Mac, usb connection is ok, because I can flash FC firmware.
> But when I try to connect Cetus Pro (FC v1.2) I receive a message "No configuration received". I tried all available FC firmwares, It does not help.

which firmware did you flash, maybe it not support for configurator？
I should check it; can you tell me where you get the FC Firmware？ Thanks

**Comment by diesel3284** [comment]
Same exact thing happened to me as ipolikarpov, the man at the top of the thread.  Also, I don't have MMF103Virtual COM Port when I check my universal serial bus controllers.  Mine says USB Composite Device.  In Device manager under ports, Betafpv help says ELTIMA VIRTUAL SERIAL PORT (COM100->COM101).  Mine says USB Serial Device (COM3).  I only tried Betaconfig to compare to Betaflight config which works great.  Now my cetus pro only has a solid green led and beeps when powered on.  Assistance would be great.
