### ISSUE TITLE
Unable to connect to LiteRadio 3 and Meteor 85 whoop

### ISSUE THREAD

**Issue by jeremyhu** [BETAFPV/BETAFPV_Configurator#20]
I'm using v1.1.1-RC1 and am attempting to update the firmware on my new LiteRadio 3 (SX1280, HW Version 1.0.0, Firmware Version 2.0.0).
I'm using macOS 12.5

I powered on the device with the setup button pressed, and BetaFPV Configurator shows the serial port (/dev/tty.usbmodem40424D4F30301).  When I click 'Connect', it errors out with:

<img width="262" alt="Screen Shot 2022-07-27 at 09 27 47" src="https://user-images.githubusercontent.com/1258676/181300057-9546718b-e82e-4290-b7bb-1dc020a09470.png">

I also get the exact same error message when connecting to my Meteor85 whoop.  I'm able to use Betaflight Configurator to connect to my Meteor85 whoop with the same serial port.

**Comment by wenzhicode** [comment]
Hi, @jeremyhu 

"I also get the exact same error message when connecting to my Meteor85 whoop. I'm able to use Betaflight Configurator to connect to my Meteor85 whoop with the same serial port."

Yes, it can just connect serial port with specific PID & VID number, it cannot used for BF flight controller.
