### ISSUE TITLE
LiteRadio won't stay selected

### ISSUE THREAD

**Issue by tranceonline** [BETAFPV/BETAFPV_Configurator#22]
Hi, everytime i select the LiteRadio 2 as the Radio and press ok, so the menu closes, and than go back in the settings, it is not selected anymore! It always jumps back to the last Radio. Every other radio works and stays selected but not the LiteRadio :/

This way i can't connect to my Radio and can't  do anything on it!
Allready tried it on two PCs. Same Result!

Help plz!

**Comment by wenzhicode** [comment]
Hi, @tranceonline, can you show me a short video for this problem?
