### ISSUE TITLE
Run As Admin - Mac

### ISSUE THREAD

**Issue by timmcwilliams** [BETAFPV/BETAFPV_Configurator#26]
Cannot get the program to run on macbook air.  It opens and will work until request Update Firmware when it shows error box asking to run as administrator which when use terminal  ---    applications/betafpv_configurator/contents/macos/betafpv_configurator

The script runs but get a cannot open error.

**Comment by wenzhicode** [comment]
Hi
I guess you should install the configurator, not use terminal to open it

**Comment by rafaerp** [comment]
Did you solve this issue?

<img width="1492" alt="Screenshot 2024-03-29 at 9 53 16 AM" src="https://github.com/BETAFPV/BETAFPV_Configurator/assets/165401626/7aac2a4b-9de4-4606-8e7b-6d30287f42e3">
