### ISSUE TITLE
The problem with the V2.0 update

### ISSUE THREAD

**Issue by vvkazakov** [BETAFPV/BETAFPV_Configurator#27]
Greetings! I have updated my BETAFPV Cetus pro drone with Seus_pro_1 firmware.2.2.bin. Updated via the BETAFPV Configurator program. After that, when the drone is connected, only one beep sounds. Nothing else is happening. There is no familiar sound about the drone's readiness to fly. There is no light indication. The drone does not connect to the glasses and the remote control. Board version V2.0 IV. Photo attached. What should I do? Please help me!
![2023-01-31 20-10-29](https://user-images.githubusercontent.com/124024040/215833709-fd628124-0a7a-4a08-b0e8-a20cdbeeb2df.JPG)
![2023-01-31 20-12-07](https://user-images.githubusercontent.com/124024040/215833716-852f8214-c910-4e23-a5b1-738e7454c452.JPG)

**Comment by vvkazakov** [comment]
Проблема решена. Это прошивка для версии 2.0.
https://drive.google.com/drive/folders/12-sqE5kJ9ttmKHKxeb52P6sKIUnDnDzw?usp=share_link

**Comment by wenzhicode** [comment]
OK, I close it
thanks
