### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by mchelifpv** [BETAFPV/BETAFPV_Configurator#3]
Can you please make a linux version of this configurator?

**Comment by HWT662988** [comment]
ok ,I am working on Linux and Mac versions now.

**Comment by cjd** [comment]
any progress?

**Comment by mchelifpv** [comment]
LiteRadio3 released, but Linux-version of configurator not...

**Comment by HWT662988** [comment]
The Linux version was complied and it runs fine on linux , Howerve ,The LiteRadio's HID protocol does not work perfectly on Linux.  So the Linux version was not released.

**Comment by mhcerri** [comment]
Hi. Does the windows version work with wine?

**Comment by rybaha** [comment]
> Hi. Does the windows version work with wine?

I was able to run it once after installation, but COM port isn't detected. I tried install STM driver, configure registry and symlink ttyACM0 device inside dosdevices folder inside wine_home, but no luck.

**Comment by rybaha** [comment]
> The Linux version was complied and it runs fine on linux system , Howerve ,The LiteRadio's HID protocol does not work perfectly on Linux. So the Linux version was not released.

Can we flash transmitter with it and configure buzzer?

**Comment by DFF-fred** [comment]
almost 2 years after the initial post/response and one year and a half since HID protocol issues was identified. Any progress?
Thank you

**Comment by Vzlom** [comment]
Hello when will there be a version for Linux?

**Comment by Vzlom** [comment]
Hello when will there be a version for Linux?

**Comment by dariotarantini** [comment]
@liyouluo @HWT662988 is there any updates on this issue?

**Comment by Vzlom** [comment]
UP

**Comment by Ficles** [comment]
Linux version when??

**Comment by LeehotYuu** [comment]
#46

**Comment by Vzlom** [comment]
> #46

Can you help me compile this for linux? Maybe i fix this problem with HID
