### ISSUE TITLE
LiteRadio 3 cc2500 +  ELRS Nano TX (ELRS v3)

### ISSUE THREAD

**Issue by astorions** [BETAFPV/BETAFPV_Configurator#34]
Good day. I have such a collection:
- BetaFPV LiteRadio 3 cc2500
- BetaFPV ELRS Nano transmission module (2.4GHz)
- happymodel mobula7 1s elrs

AFTER updating the ELRS Nano module to ELRS 3.2.1 and updating mobula7, the transmitter binded with the drone, but the LiteRadio 3 does not work. When I connected BetaFPV ELRS Nano to TBS Tango 2, everything works fine. Does LiteRadio 3 support the BetaFPV ELRS Nano module flashed to ELRS version 3?

**Comment by maxim-magpaylabs** [comment]
I have the same problem, its imperative to get the literadio3 to work with the nano module on the elrs 3. Are there any updates coming?

**Comment by Omelya** [comment]
I have the same problem, help me figure it out

**Comment by f2003911** [comment]
need update,or i can only choose to sell my literadio3

**Comment by X-ForceFPV** [comment]
It's time my chinese friends...
this is really overdue, especially since you advertise the nano module for the literadio3.
while you are at it, pls also update the literadio3 to the newest elrs.

**Comment by yeuem1vannam** [comment]
Please support ELRS 3.0 to the Lite Radio 3.

**Comment by I297I** [comment]
https://support.betafpv.com/hc/en-us/articles/22404447195673-How-to-Update-ELRS-V2-to-ELRS-V3-Test-Version

**Comment by astorions** [comment]
> https://support.betafpv.com/hc/en-us/articles/22404447195673-How-to-Update-ELRS-V2-to-ELRS-V3-Test-Version

The topic of the question indicates cc2500, but here the solution is only for SX1280. Has anyone managed to solve the problem with the cc2500?

**Comment by LeehotYuu** [comment]
This issue has been a long time coming, I'll try to make a reply and close this issue.
For both ELRS (SX128x) and Frsky (CC2500), please update the firmware to 20241108 or higher to get the latest support, currently you can use an external RF, but you can't configure the specific parameters via BETAFPV Configurator yet.
Update method reference:
#55
