### ISSUE TITLE
What are the steps to build BETAFPV_Configurator for macOS?

### ISSUE THREAD

**Issue by valeriyvan** [BETAFPV/BETAFPV_Configurator#36]

**Comment by OliverDobner** [comment]
Just want to bring this up, why is there noch macOS version for the 2.0RC release? @wenzhicode

**Comment by Andy-Chase** [comment]
I agree, this is super frustrating. I can't upgrade my firmware so now my radio is just a paperweight. It would be super helpful to get a macos version.

**Comment by LeehotYuu** [comment]
I've actually finished the .dmg files and will be releasing them soon after completing some necessary testing.

**Comment by Andy-Chase** [comment]
Fantastic. Thanks, I look forward to seeing this released!
