### ISSUE TITLE
BETAFPV Configurator 2.0 does not connect to my Literadio 3

### ISSUE THREAD

**Issue by Slint7** [BETAFPV/BETAFPV_Configurator#38]
BETAFPV Configurator 2.0 does not connect to my Literadio 3, but BETAFPV Configurator 1.1.1 does.

I already installed STM32 Virtual COM Port Driver and ran it from program files.

**Comment by SozinovD** [comment]
I also have this issue after updating radio to newest software version
When i downgrade it to elrs 2.0.1 it works with configurator 1.1.1 fine, but i need elsr 3.x.x on my radio

**Comment by alloyking** [comment]
Same here.  The com port selection stays in "loading" status.  It's not detecting ports.

**Comment by Keith362** [comment]
It does the same for me as will so its back to v1.1.1

**Comment by Xb0X** [comment]
Same here... I can't even use it in simulators like lift off. Windows detect it when it's plugged, I've got the usb sound, but in the device manager the usb device has a warning sign.

Also I tried install the STM32 Virtual COM Port Driver but nothing changed.

I'm running on windows 11

**Comment by Keith362** [comment]
Hope they can fix it soon to, I don't like using old versions.

**Comment by Slint7** [comment]
I got mine working after having the same problem. Make sure you are using
the correct software version and that you hold in the setup button when
powering on the remote.

**Comment by Keith362** [comment]
@Slint7
I don't need to hold down the setup button on v1.1.0 so why should I do it with this version ?

**Comment by Slint7** [comment]
The new version is different. Also 1.1.0 doesn't work. Use the latest
version.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Keith362** [comment]
v1.1.0 works good for me, not that I use it a lot.
Just wish they can fix the new version.

**Comment by Slint7** [comment]
You can change settings on v1, but not update firmware.

**Comment by Slint7** [comment]
The new app works if you do it correctly.

**Comment by Xb0X** [comment]
I tried all your solutions guys...

Pay attention it's off...
Try to click setup when switching on...

But none of these work for me 😢

**Comment by DEMs86** [comment]
i have the same problem, Windows 10, after connection (on switched off controller) no any XOM ports available/ In device manager i can see only one USB device with yellow error. 
Any ideas for select drivers of update, have no results. 
![image](https://github.com/BETAFPV/BETAFPV_Configurator/assets/104394693/0f521651-09eb-4e3c-8f88-71d583e7add0)

**Comment by alloyking** [comment]
"Holding down the setup button while plugging in the cable" - I want point out that this allowed me to flash a bin file that I downloaded.  BUT none of the dropdown's, etc works.   So if you are trying to flash you should be able to do that.  Just don't expect the UI to do too much.  I flashed a liteRadio 3 to the elrs3 version to work with BetaFlight Config 4.4.3.

**Comment by alloyking** [comment]
Also if you want to just configure the remote (not flash it) then plug in the remote (WHEN OFF) and then click the connect button.

**Comment by Keith362** [comment]
@alloyking
I try that and still doesn't for me, So I had to go back to the old version (Damn)

**Comment by alloyking** [comment]
@Keith362 - Well the only thing this 2.0RC version is good for is updating to ELRS V3.0.   If you are not trying to do that, then don't bother for sure.

**Comment by Keith362** [comment]
Thanks alloyking for the info on this one..
Merry Christmes as will.

**Comment by afarinetti** [comment]
Data point: I was able to get my BetaFPV LiteRadio 3 to work in v2.0-RC2 by flashing the firmware to 3.0.0.

**Comment by DEMs86** [comment]
It is worked on another desktop/laptop. I think the problem in my PC with sone drivers, may be problems with specific hardware. But, all what i can say, i have no problem to connect RC2.0 with LiteRadio ELRS 3.0 on another device. 

> i have the same problem, Windows 10, after connection (on switched off controller) no any COM ports available/ In device manager i can see only one USB device with yellow error. Any ideas for select drivers of update, have no results. ![image](https://private-user-images.githubusercontent.com/104394693/291104435-0f521651-09eb-4e3c-8f88-71d583e7add0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjU1MTYsIm5iZiI6MTcwNDY2NTIxNiwicGF0aCI6Ii8xMDQzOTQ2OTMvMjkxMTA0NDM1LTBmNTIxNjUxLTA5ZWItNGUzYy04Zjg4LTcxZDU4M2U3YWRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QyMjA2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGUxYjM0OTQzNjFlYzA0YThlYzliNGI4OGEwYzdiMGI3MWFkZDhhMTJmZDYzM2M1M2M0YmI2YTFmOWIxZmFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LagSrWuJsqNA841OUuP9PPVyzh7zyDlrkZT8nNOJsew)

**Comment by Keith362** [comment]
When are they going t fix this app, so I can start using it again ?

**Comment by Keith362** [comment]
Never buying BETAFPV  Drones again if they can't fix there App Up.

**Comment by Edikscrmp** [comment]
> i have the same problem, Windows 10, after connection (on switched off controller) no any COM ports available/ In device manager i can see only one USB device with yellow error. Any ideas for select drivers of update, have no results. ![image](https://private-user-images.githubusercontent.com/104394693/291104435-0f521651-09eb-4e3c-8f88-71d583e7add0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjk5NTYsIm5iZiI6MTcxMzM2OTY1NiwicGF0aCI6Ii8xMDQzOTQ2OTMvMjkxMTA0NDM1LTBmNTIxNjUxLTA5ZWItNGUzYy04Zjg4LTcxZDU4M2U3YWRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxN1QxNjAwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTNiMmU1YTliNjQ5ZDc1ZDE2MDY0NjljMTE3MTYyYjMwMDA3NzY4YWNlNmY2Njk1MTk1YzVjZjI1OTYxYjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NquQxTFJyTPQGVPXfZyQSG4KV_Fr0pY0mHoxlQpTa5Y)

Same problem. I already tried to install any drivers, but its not work.

**Comment by Keith362** [comment]
Yes I lot of People are having the same Problem
But know one cares about fixing it. 
I have sold my BetaFPV Drone now and Never buying another one ever again..

**Comment by LeehotYuu** [comment]
It's been a long time since this issue, and I'm not sure my response is still valid because so much has happened in a year.
If anyone else with the same concerns sees this issue, please use the latest release of BETAFPV Configurator V2.0 official version and upgrade the RC firmware to version 20241108 or higher, many of the bugs may have been fixed.
After doing the above, if there are still any new issues, please open a new issue.

**Comment by askrinnik** [comment]
> Betafpv is junk... Wish I never wasted my money on this crap. None of the directions work with win 11, holding the setup and powering on, etc.. Pure crap, never got the stupid thing to connect to beta fpv configurator.

None of all BTEAFPV production is junk
A lot of people are happy with the Meteor and Air drone series.

**Comment by derasmo1976** [comment]
> > Betafpv is junk... Wish I never wasted my money on this crap. None of the directions work with win 11, holding the setup and powering on, etc.. Pure crap, never got the stupid thing to connect to beta fpv configurator.
> 
> None of all BTEAFPV production is junk A lot of people are happy with the Meteor and Air drone series.

I take this back, I got it to work. I have the beta lite fpv 3 PRO which I found out uses OpenTX. So I updated it in elrs configurator and updated the firmware in EdgeTX. I still wish it would work with betafpv configurator so I can test the controller.

**Comment by askrinnik** [comment]
> > > Betafpv is junk... Wish I never wasted my money on this crap. None of the directions work with win 11, holding the setup and powering on, etc.. Pure crap, never got the stupid thing to connect to beta fpv configurator.
> > 
> > 
> > None of all BTEAFPV production is junk A lot of people are happy with the Meteor and Air drone series.
> 
> I take this back, I got it to work. I have the beta lite fpv 3 PRO which I found out uses OpenTX. So I updated it in elrs configurator and updated the firmware in EdgeTX. I still wish it would work with betafpv configurator so I can test the controller.

If you use betafpv literadio 3 PRO, you don't need to connect it to the betafpv configurator. Edge TX is configured another way
