### ISSUE TITLE
BetaFPV Radio Naming Problem

### ISSUE THREAD

**Issue by Nuwr1** [BETAFPV/BETAFPV_Configurator#41]
Many confuse because of Manufacturer radio Production version is unidentified able.

This will let you all afterall my research that BetaFPV unclear answear after i asked them.

They may have language problem, translating conversation hardly in english.

So...
This is the real name version :
LiteRadio : can cause you all confuse see below

Version name is :

LiteRadio 1
LiteRadio 2
LiteRadio 2 SE is : LiteRadio 2 SE v1 frsky
And then LiteRadio 2 SE v1 ELRS
LiteRadio 2 SE v2 Frsky
LiteRadio 2 SE v2 ELRS
LiteRadio 3

**Comment by LeehotYuu** [comment]
Thank you very much for your summary of LiteRadio naming, and using the LiteRadio 2 SE V2 ELRS as an example, I will explain the name meaning.
* “2” is the series, which often corresponds to the RC form factor;
* “SE” is a functional designation, which indicates a lower level of functionality for the same series;
* “V2” is the new PCB version, for the same series, V2 and V1 are simply the same form factor, but are two completely different RCs;
* “ELRS” stands for the software protocol supported by the hardware RF chip, ELRS is the SX128x chip and Frsky is the CC2500 chip.
