### ISSUE TITLE
elrs version&upgrade

### ISSUE THREAD

**Issue by kongzheng333** [BETAFPV/BETAFPV_Configurator#5]
elrs version doesn't show on the configurator，firmware upgrade function is not available as well，so are these functions expected to be realized in a later release?

**Comment by HWT662988** [comment]
Sorry for the late reply，The ELRS version of the Flight control uses the Betaflight firmware，so you'll need to use the Betaflight Configurator  to upgrade it，the firmware 1.2.0 can be downloaded here：[betaflight_BETAFPVF4SX1280.hex](https://github.com/betaflight/betaflight/pull/10788)![image](https://user-images.githubusercontent.com/45007731/143354861-15eab807-0eb8-4c73-989b-9a3b0c5d7682.png)
