### ISSUE TITLE
Literadio 3 is Corrupted firmware

### ISSUE THREAD

**Issue by MulamboLoko** [BETAFPV/BETAFPV_Configurator#50]
I'm having trouble updating my BetaFPV Literadio 3. During the process, there was a power outage, and since then, it's been corrupted. The controller doesn't respond, and it doesn't power on or show any lights when plugged into USB. When connected to the computer, it's not recognized as a device, but Windows detects that something is connected to the USB port. I think I need to reset it to factory settings now. Where should I start?

**Comment by LeehotYuu** [comment]
Check if your RC is Frsky or ELRS and re-flash it.
Latest LR3 firmware url:
https://support.betafpv.com/hc/en-us/articles/4414348993177-Lite-Radio-3
