### ISSUE TITLE
请及时更新1.1的ELRS SPI飞控固件

### ISSUE THREAD

**Issue by zhoumigo** [BETAFPV/BETAFPV_Configurator#6]
1

**Comment by HWT662988** [comment]
ELRS SPI 1.2版本飞控固件可以在这里下载： [betaflight_BETAFPVF4SX1280.hex](https://github.com/betaflight/betaflight/pull/10788)![image](https://user-images.githubusercontent.com/45007731/143359120-849c16a8-512e-48bb-aa7f-facd55804f50.png)
注意：ELRS SPI飞控使用的是betaflight固件，所以需要使用Betaflight Configurator地面站更新和配置。

**Comment by acemaxkimo** [comment]
> ELRS SPI 1.2版本飞控固件可以在这里找到： [#10788](https://github.com/betaflight/betaflight/pull/10788#issuecomment-969890885)
> 
> [betaflight_4.3.0_BETAFPVF4SX1280_0265565fa.zip](https://github.com/betaflight/betaflight/files/7543689/betaflight_4.3.0_BETAFPVF4SX1280_0265565fa.zip)
> 
> 注意：ELRS SPI飞控使用的是betaflight固件，需要使用Betaflight Configurator地面站更新和配置。

請問有BetaFPV ELRS 2.0 SPI的 BF固件了嗎?
