### ISSUE TITLE
No OSD on Cetus PRO after Flash FC

### ISSUE THREAD

**Issue by m4rc1no5** [BETAFPV/BETAFPV_Configurator#7]
Hello,

After flash firmware (1.1.1 or 1.1.2) on Cetus PRO I don't see any information (about fly time, mode, battery voltage) on the screen. There is only a raw view from the camera. Could you help me and tell me what I should do to enable this information - I don't see this option in BETAFPV Configurator (v1.1.0_RC1).

Best regards,
Marcin Zaremba

**Comment by m4rc1no5** [comment]
I tested firmware 1.1.1 and 1.1.2 and I use BETAFPV Configurator on macOS. Thanks.

**Comment by HWT662988** [comment]
Did the OSD work properly before you updated the new firmware?and could you tell me your FC's hardware version (such as 'lite 1-2S Pro1.1' or 'Cetus pro1.2')which you can see on flight control board?  Thanks.

**Comment by m4rc1no5** [comment]
Hi,

The OSD worked properly before the update. 

I see on the FC version `Lite 1-2S Pro`.

Thanks for fast your response. :)

**Comment by m4rc1no5** [comment]
Hi,

everything works fine after updating OSD firmware - thank you very much for your support! :)

Best regards,
Marcin

**Comment by LeMysticboy** [comment]
@HWT662988  I Have a similar problem. I updatet the FC Firmware to V1.2.2 on my Cetus Pro Brushless. 
Now i lost the OSD. I tried to flash a new OSD Firmware. but it don't worked. I think i have the wrong OSD firmware. 

could you sent me the correct OSD Firmware?

My Setup:
Cetus Pro Brushless 
FC Board V1.2 
FC firmware version V1.2.2
